### ISSUE TITLE
I forked your Repo

### ISSUE THREAD

**Issue by DO1JLR** [diodonfrost/ansible-role-ntp#1]
Hi @diodonfrost 

I "forked" your repo and did some changes:
[github.com/chaos-bodensee/role-ntp](https://github.com/chaos-bodensee/role-ntp.git)

And I did not told you.

Maybe you are interested in merging it into one repo?

**Comment by diodonfrost** [comment]
Hello @DO1JLR 

Feel free to submit pull requests
